# Generated by Django 5.2.4 on 2026-02-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
