# Generated by Django 5.2.4 on 2026-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerprofile',
            name='fssai_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='baker_documents/'),
        ),
    ]
