# Generated by Django 5.2.4 on 2026-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bakerprofile_fssai_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_address',
            field=models.TextField(blank=True, help_text='Default delivery address'),
        ),
    ]
