# Generated by Django 5.2.4 on 2026-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerprofile',
            name='accepts_custom_orders',
            field=models.BooleanField(default=True, help_text='Accept custom cake orders'),
        ),
    ]
