# Generated by Django 5.2.4 on 2026-02-11 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bakerprofile_accepts_custom_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_image', models.ImageField(upload_to='photo_cakes/')),
                ('description', models.TextField()),
                ('flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('red_velvet', 'Red Velvet'), ('strawberry', 'Strawberry'), ('butterscotch', 'Butterscotch'), ('fruit', 'Fruit'), ('black_forest', 'Black Forest'), ('pineapple', 'Pineapple'), ('mango', 'Mango')], max_length=50)),
                ('size', models.CharField(help_text='e.g. 1kg, 2kg', max_length=50)),
                ('delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_cake_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo Cake Request',
                'verbose_name_plural': 'Photo Cake Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
