# Generated by Django 5.2.4 on 2026-02-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_photocakerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('AI', 'AI Designed'), ('PHOTO', 'Photo Reference')], max_length=10)),
                ('reference_image', models.ImageField(upload_to='custom_requests/')),
                ('description', models.TextField()),
                ('flavor', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('price_quote', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('baker_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to='main.bakerprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cake_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Cake Request',
                'verbose_name_plural': 'Custom Cake Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PhotoCakeRequest',
        ),
    ]
