# Generated by Django 5.2.4 on 2026-02-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_delivered_at_order_delivery_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_otp',
            field=models.CharField(blank=True, help_text='4-digit order confirmation OTP', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('baking', 'Baking'), ('packing', 'Packing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
    ]
