# Generated by Django 5.2.4 on 2026-03-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_userprofile_email_otp_userprofile_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='source',
            field=models.CharField(choices=[('recharge', 'Wallet Recharge'), ('refund', 'Order Refund'), ('order', 'Order Payment'), ('cashback', 'Cashback'), ('commission', 'Commission'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
    ]
