# Generated by Django 5.2.4 on 2026-03-12 15:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_cake_stock_quantity_alter_wallet_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_baking', 'Order Baking'), ('order_ready', 'Order Ready'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('review_received', 'Review Received'), ('baker_approved', 'Baker Approved'), ('baker_rejected', 'Baker Rejected'), ('payment_received', 'Payment Received'), ('low_stock', 'Low Stock Alert'), ('custom_request_accepted', 'Custom Request Accepted'), ('custom_request_rejected', 'Custom Request Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
