# Generated by Django 5.2.4 on 2026-03-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerprofile',
            name='license_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
