# Generated by Django 5.2.4 on 2026-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_bakerprofile_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('baker', 'Baker'), ('admin', 'Admin'), ('delivery_assistant', 'Delivery Assistant')], default='customer', max_length=20),
        ),
    ]
