# Generated by Django 5.2.4 on 2026-03-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_supportticket_websitereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='resolution_message',
            field=models.TextField(blank=True, help_text='Optional message from admin when resolving', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_baking', 'Order Baking'), ('order_ready', 'Order Ready'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('review_received', 'Review Received'), ('baker_approved', 'Baker Approved'), ('baker_rejected', 'Baker Rejected'), ('payment_received', 'Payment Received'), ('low_stock', 'Low Stock Alert'), ('custom_request_accepted', 'Custom Request Accepted'), ('custom_request_rejected', 'Custom Request Rejected'), ('ticket_resolved', 'Support Ticket Resolved')], max_length=50),
        ),
    ]
