# Generated by Django 5.2.4 on 2026-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_add_coupon_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount applied via coupon code', max_digits=10),
        ),
    ]
