# Generated by Django 5.2.4 on 2026-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_add_coupon_discount_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_baking', 'Order Baking'), ('order_ready', 'Order Ready'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('review_received', 'Review Received'), ('baker_approved', 'Baker Approved'), ('baker_rejected', 'Baker Rejected'), ('payment_received', 'Payment Received'), ('low_stock', 'Low Stock Alert'), ('custom_request_accepted', 'Custom Request Accepted'), ('custom_request_rejected', 'Custom Request Rejected'), ('ticket_resolved', 'Support Ticket Resolved'), ('coupon_launched', 'New Coupon Launched')], max_length=50),
        ),
    ]
