# Generated by Django 5.2.4 on 2026-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_letter_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customcakerequest',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_requests/'),
        ),
    ]
